export const MUTATION_TYPES = {
  SET_PRODUCTS_LIST: "SET_PRODUCTS_LIST",
  SET_PRODUCTS_VALUE: "SET_PRODUCTS_VALUE",
  ADD_PRODUCT: "ADD_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_PRODUCT_QUANTITY: "UPDATE_PRODUCT_QUANTITY",
  DELETE_FROM_CART: "DELETE_FROM_CART",
};
